version: "3.8"

services:


   webserver:
    container_name: wordpress
    image: wordpress:latest
    restart: always
    ports:
     - 80:80
    depends_on: 
     - db
    networks: 
     - frontend
    environment: 
     - WORDPRESS_DB_HOST=db
     - WORDPRESS_DB_USER=user
     - WORDPRESS_DB_PASSWORD=password
     - WORDPRESS_DB_NAME=database
    volumes: 
     - $PWD:/var/www/html/wp-content:rw

   db:
    container_name: mysql
    image: mysql:latest
    restart: always
    networks: 
     - frontend
    environment: 
     - MYSQL_DATABASE=data
     - MYSQL_USER=user
     - MYSQL_PASSWORD=password
     - MYSQL_RANDOM_ROOT_PASSWORD=superpassword
    volumes: 
     - mydb:/var/lib/mysql:rw

networks:
  frontend:
volumes:
  mydb:
