version: "3.8"

services:


   wordpress:
    container_name: wordpress
    image: wordpress:latest
    restart: always
    ports:
     - 80:80
    depends_on: 
     - mysql
    networks: 
     - wordpress
    environment: 
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
     - wordpress_data:/var/www/html

   mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    networks: 
     - wordpress
    environment: 
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
     - mysql_data:/var/lib/mysql

networks:
  wordpress:

volumes:
  wordpress_data:
  mysql_data: