version: "3.3"

services:


   webserver:
    container_name: nginx
    image: nginx:latest
    ports:
     - 9191:80
    networks: 
     - frontend
    volumes:
     - vol3:/usr/share/nginx/html

networks:
  frontend:

volumes:
  vol3: